"""add created_at and updated_at to user model

Revision ID: 0901fbaef868
Revises: d0e502969642
Create Date: 2023-06-06 20:23:43.564188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0901fbaef868'
down_revision = 'd0e502969642'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
