"""add created_at and updated_at to user model

Revision ID: 247890630376
Revises: a3e98c83c919
Create Date: 2023-06-06 20:41:58.790150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '247890630376'
down_revision = 'a3e98c83c919'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
