"""add created_at and updated_at to user model

Revision ID: 7275da031980
Revises: 80469c1c7133
Create Date: 2023-06-06 20:30:44.367814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7275da031980'
down_revision = '80469c1c7133'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
