"""add created_at and updated_at to user model

Revision ID: 80469c1c7133
Revises: 0901fbaef868
Create Date: 2023-06-06 20:25:55.151254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80469c1c7133'
down_revision = '0901fbaef868'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
