"""add created_at and updated_at to user model

Revision ID: a3e98c83c919
Revises: 8c36a5fe1d7b
Create Date: 2023-06-06 20:34:24.359403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3e98c83c919'
down_revision = '8c36a5fe1d7b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
